@startuml
!include Style.puml

skinparam nodesep 100

class Exception {
    - message: String
    + Exception(message: String)
    + getMessage(): String
}

class ParseException {
    + ParseException(message: String)
}

class ParseBlankCommandException {
    + ParseBlankCommandException()
}

class ParseUnknownCommandException {
    + ParseUnknownCommandException(message: String)
}

class ParseInvalidArgumentException {
    - usages: String[]
    + ParseInvalidArgumentException(message: String, usages: String[])
    + getUsages(): String[]
}

Exception <|-- ParseException
ParseException <|-- ParseBlankCommandException
ParseException <|-- ParseUnknownCommandException
ParseException <|-- ParseInvalidArgumentException

@enduml